//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using FluentNHibernate.Mapping;
using NHibernate;
using NHibernate.Criterion;
using FluentNHibernate;
using Brandy.Grapes.FluentNHibernate;
using Brandy.Grapes;

namespace DataModel.libDB
{

    

	// nwSystype has a core Name and LongName
	// Can be Listed Found etc
    public class nwdbDataType 
    {
        
        
        //Properties
        public virtual int id { get; protected set; }
        public virtual string Name { get; set; }
        public virtual string LongName { get; set; }

        protected  bool bUseShort;

        public nwdbDataType() {
            if (this.Name == null) { this.Name = ""; }
            if (this.LongName == null) { this.LongName =""; }
        }

        public nwdbDataType(string n, string nl): this()
        {
            if (n.Length > nwdbConst.LEN_SHORT || nl.Length > nwdbConst.LEN_LONG)
            {
                throw new ApplicationException("Name Value too long, truncate Shortname"+n+",LongName"+nl);
            }
            
            this.Name = n.Substring(0, Math.Min(nwdbConst.LEN_SHORT , n.Length ));
            this.LongName = nl.Substring(0, Math.Min(nwdbConst.LEN_LONG , nl.Length ));
            //this.Name = n;
            //this.LongName = nl;
        }

        //Methods
        //overwrite this to get better output
        protected virtual string toStringImpl()
        {
            if (bUseShort) { return this.Name; } else { return this.LongName; }
        }

        protected virtual string ToLongString()
        {
            return "ID " + this.id.ToString() + " Name:" + this.Name + " LongName:" + this.LongName;
        }

        // crap for printing & finding
        public override string ToString()
        {
            return toStringImpl();
        }
       

    }

    /* A GroupedType will have a nwdbTree for managing the grouping Heirarchy
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     * */


    public class nwSystemGroupedType : nwdbDataType
    {
        public virtual nwdbTree Category { get; set; }

        public nwSystemGroupedType() : base() { }
        public nwSystemGroupedType(string n, string nl) : base(n, nl) { }
        public nwSystemGroupedType(string n, string nl,nwdbTree st) : base(n, nl) {
            Category = st;
        }

    }
}

