//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;
using norwold.model;


namespace DataModel
{
	[TestFixture()]
	public class nu_libdata
	{
        nwdbConnection db = new nwdbConnection();


		//[Test()]
		public void TestCase ()
		{
		}
	}
}

